### ISSUE TITLE
Loading the xontrib on xonsh 0.14.0 causes xonsh to become a background process.

### ISSUE THREAD

**Issue by skaphi** [74th/xonsh-direnv#14]
In this newer version of xonsh, when loading this xontrib in my rc-file, it causes xonsh to become a background process in bash instead of launching xonsh. 

```
~ ✦ [18:56:59] ❯ xonsh
[2]+  Stopped                 xonsh

✦ [18:56:37] ❯ 
```

The problem appears to be related to spawning a subshell in `@events.on_post_rc`

I created this minimal xonsh-rc to create the same issue.

```
@events.on_post_rc
def __direnv_post_rc():
    r = $(ls)
```

I will create the same issue in the main xonsh repo as well.

**Comment by con-f-use** [comment]
Closed because [upstream issue](https://github.com/xonsh/xonsh/issues/5244)
