### ISSUE TITLE
License

### ISSUE THREAD

**Issue by t184256** [74th/xonsh-direnv#4]
Please pick a license for your project, AFAIK one cannot use it, let alone package it without one.

**Comment by 74th** [comment]
Yes. This uses MIT License. https://github.com/74th/xonsh-direnv/blob/master/setup.py#L9

**Comment by t184256** [comment]
Ooh, thanks. I've overlooked that. Please, add a LICENSE file anyway, preferably in a way that gets picked up by Github, so that you won't get bothered with that question again.

**Comment by 74th** [comment]
https://github.com/74th/xonsh-direnv/commit/edb30992763655266982a826296864d92d91c9b8
