### ISSUE TITLE
Add tags to repo

### ISSUE THREAD

**Issue by anki-code** [74th/xonsh-direnv#8]
Hi! Thank you for the useful xontrib!

Please add `xonsh` and `xontrib` tags to the repo:

![image](https://user-images.githubusercontent.com/1708680/94840154-a940e880-0420-11eb-8d2d-d99bd2d71959.png)

It helps spread the word about xontrib on Github.

Thanks!

**Comment by 74th** [comment]
Thank you for your suggestion!
I added them.
